apiVersion: apps/v1
kind: Deployment
metadata:
  name: celery-beat
  labels:
    app: celery-beat
spec:
  replicas: {{ .Values.worker.replicas }}
  selector:
    matchLabels:
      pod: celery-beat
  template:
    metadata:
      labels:
        pod: celery-beat
    spec:
      containers:
      - name: celery-beat
        image: {{ .Values.global.repository | quote }}
        command: ['celery', '-A', 'base_app', 'beat', '-l', 'debug']
        env:
        {{- include "charts.env" . | nindent 8 }}
        - name: POSTGRES_HOST
          value: {{ .Values.global.postgres.host }}
        - name: REDIS_HOST
          value: {{ .Values.global.redis.host }}
