apiVersion: apps/v1
kind: Deployment
metadata:
  name: celery-worker
  labels:
    deployment: celery-worker
spec:
  replicas: {{ .Values.worker.replicas }}
  selector:
    matchLabels:
      pod: celery-worker
  template:
    metadata:
      labels:
        pod: celery-worker
    spec:
      containers:
      - name: celery-worker
        image: {{ .Values.global.repository | quote }}
        command: ['celery', '-A', 'base_app', 'worker', '-l', 'info']
        env:
        {{- include "charts.env" . | nindent 8 }}
        - name: POSTGRES_HOST
          value: {{ .Values.global.postgres.host }}
        - name: REDIS_HOST
          value: {{ .Values.global.redis.host }}
