{{ if eq .Values.global.env "local" }}
kind: PersistentVolume
apiVersion: v1
metadata:
  name: {{ include "postgres.fullname" . }}
  labels:
    {{- include "postgres.labels" . | nindent 4 }}
spec:
  capacity:
    storage: 2Gi
  storageClassName: standard
  accessModes:
    - ReadWriteMany
  hostPath:
    type: DirectoryOrCreate
    path: /data/postgres-pv
{{ end }}
