# Default values for auth.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
image:
  repository: gcr.io/composite-keel-269505/auth
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  port: 8080

resources: 
  limits:
    cpu: 100m
    memory: 300Mi
  requests:
    cpu: 100m
    memory: 280Mi

credentials:
  placesApi:
    token: AIzaSyCyOceoFGw8n_lopxTxLuL-OXoatF21jWE