apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.global.redis.host }}
  labels:
    {{- include "redis.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
  selector:
    {{- include "redis.selectorLabels" . | nindent 4 }}
